### ISSUE TITLE
Cost function overwriting

### ISSUE THREAD

**Issue by jcallaham** [UW-AMO/sr3-matlab#1]
The cost function R(w) on lines 65 and 136 gets overwritten by a matrix R from the QR decomposition on line 104.   I fixed it locally be renaming the function - let me know if you want me to push.

Error from sr3_demo.m:
Array indices must be positive integers or logical values.

Error in sr3 (line 136)
    obj = 0.5*sum((A*x-b).^2) + lam*R(w) + 0.5*kap*sum((y-w).^2);

Error in sr3_demo (line 67)
[x0, w0] = sr3(A, b, 'mode', '0', 'lam',lam0,'ptf',0);

**Comment by askhamwhat** [comment]
Ah, yes, that was from a dumb search and replace to match the paper's syntax. Please submit a pull request.
