### ISSUE TITLE
Wrong Variable Name Throws Error in sr3.m

### ISSUE THREAD

**Issue by PinkyKohl** [UW-AMO/sr3-matlab#3]
I got the following, when setting 'mode' to 'mixed':

Not enough input arguments.

Error in mode (line 58)
if isstring(x)

Error in sr3>sr3_parse_input (line 220)
            || strcmp(p.Results.mode,'2') || strcmp(mode,'mixed')

It seemes to work now with p.Results.mode instead of mode in line 220 (and 227 while we are at it)

**Comment by askhamwhat** [comment]
thanks for pointing this out!
